from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src = ['main.c']
src += ['lcd.c']
src += ['i2c_scan.c']
src += ['jsmn.c']
src += ['event_handler.c']
src += ['card_reader.c']
src += ['app.c']
src += ['mqtt_link.c']

if GetDepend(['PKG_USING_RTDUINO']) and not GetDepend(['RTDUINO_NO_SETUP_LOOP']):
    src += ['arduino_main.cpp']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
